package com.bank.islamic.wadiahsafekeepingaccount;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Wadiah Safekeeping Account
 *
 * Business Area:      Deposits and Investment Accounts
 * Business Domain:    Islamic Deposits
 * Functional Pattern: Fulfill
 * Asset Type:         Wadiah Custody Account
 * Control Record:     Wadiah Custody Account Fulfillment Arrangement
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Wadiah Safekeeping Account — BIAN Semantic API")
                .description("Service Domain 'Wadiah Safekeeping Account' (Fulfill pattern) "
                        + "operating on the 'Wadiah Custody Account Fulfillment Arrangement' control record.")
                .version("0.1.0"));
    }
}
